apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends  
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: panosagg/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagepullPolicy: {{ .Values.image.PullPolicy }}
        name: techtrends
        resources: {{ toYaml .Values.resources | indent 12 }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        livenessProbe:
           httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.containerPort }}
        readinessProbe:
           httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.containerPort }}
            
