apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  techtrends-production
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: project/helm
    repoURL: https://github.com/panosagg/udacity_TechTrends_project
    targetRevision: HEAD
