name: TechTrends - Package with Docker
on:
  push:
    branches: [ main ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set  QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set  Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login  DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./project/techtrends
          platforms: linux/amd64
          push: true
          tags: alexioy/techtrends:latest
